version: "3.7"

services:
  app:
    container_name: test-app-ci-cd
    build:
        context: .
        dockerfile: Dockerfile
    image: test-ci-cd-app
    restart: unless-stopped
    ports:
        - "8040:8000"
    volumes:
        - ./:/app:delegated
    command: php artisan serve --host=0.0.0.0 --port=8000
