apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-ci-cd-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: test-ci-cd-app-container
  template:
    metadata:
      labels:
        app: test-ci-cd-app-container
    spec:
      hostNetwork: true
      containers:
      - name: test-ci-cd-app-container
        image: ayvafe/test-ci-cd-app:latest
        ports:
        - containerPort: 8040
