
apiVersion: v1
kind: Service
metadata:
  name: test-service 
spec:
  type: NodePort
  selector:
    app: test-ci-cd-app-container
  ports:
  - name: http
    port: 8041 # The port on which the service will be exposed
    targetPort: 8040
    nodePort: 30002
