name: Deploy to Kubernetes

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      DOCKER_IMAGE_NAME: "test-ci-cd"
      EKS_CLUSTER_NAME: "elemento-dev-k8s"
      EKS_CLUSTER_NAMESPACE: "propmgmt-dev"
      EKS_CLUSTER_REGION: "us-east-2"
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
      
    - name: Build Docker image | Tag | Push
      run: |
        docker build -t "${{ env.DOCKER_IMAGE_NAME }}" .
        docker tag test-ci-cd:latest develemento/test-ci-cd:1.0.0
        docker push develemento/test-ci-cd:1.0.0
            
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.EKS_CLUSTER_REGION }}

    - name: Connect to EKS cluster
      run: |
        aws eks update-kubeconfig --name ${{ env.EKS_CLUSTER_NAME }} --region ${{ env.EKS_CLUSTER_REGION }}

    - name: Deploy to Kubernetes
      run: kubectl apply -f kubernetes/create_deployment.yml
