name: Deploy to Kubernetes

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      DOCKER_IMAGE_NAME: "test-app-ci-cd"
      DOCKER_USERNAME: "ayvafe"
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
      
    - name: Build Docker image | Tag | Push
      run: |
        docker-compose build 
        docker tag "$DOCKER_IMAGE_NAME" "ayvafe/$DOCKER_IMAGE_NAME"
        docker push "ayvafe/$DOCKER_IMAGE_NAME"

    - name: Configure Kubernetes CLI
      uses: azure/setup-kubectl@v1
      with:
        kubeconfig: ${{ secrets.KUBECONFIG }}

    - name: Deploy to Kubernetes
      run: kubectl apply -f kubernetes/create-pod.yml -f kubernetes/create-service-2.yml
